apiVersion: v1
kind: Namespace
metadata:
  name: aneci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-app
  namespace: aneci
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-app
  template:
    metadata:
      labels:
        app: grpc-app
    spec:
      containers:
        - name: grpc-app
          image: aaneci/grpc-sample-app
          ports:
            - containerPort: 5300
          resources:
            limits:
              cpu: 1500m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 100Mi
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb-grpc-app
  namespace: aneci
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: grpc-app
---

apiVersion: v1
kind: Service
metadata:
  name: grpc-app
  namespace: aneci
  labels:
    app: grpc-app
  annotations:
    contour.heptio.com/upstream-protocol.h2c: "8080"
spec:
  ports:
    - port: 8080
      targetPort: 5300
  selector:
    app: grpc-app

---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: grpc-app
  namespace: aneci
  annotations:
    kubernetes.io/ingress.class: <ingress_class>
spec:
  virtualhost:
    fqdn: <your_fqdn>
    tls:
      secretName: <tls_secret>
  routes:
    - match: /
      services:
        - name: grpc-app
          port: 8080
      permitInsecure: true
